In [1]:
import scipy.constants as const
import csv
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error as mse
from math import sqrt
import os

In [2]:
os.chdir('/Users/padamson/projects/chimpr/bl_angus/kosarim_reproduce/')

In [3]:
pi = const.pi
e = const.e
e0= const.epsilon_0

In [4]:
eV_per_J = const.physical_constants["joule-electron volt relationship"][0]
cm_per_m = 100.0

In [5]:
table2_ref = np.loadtxt(open("kosarim_table_2.csv", "rb"), delimiter=" ", skiprows=1)
table2_ref

array([[ 0.  , 15.8 , 15.4 ,  0.82,  2.1 ,  3.4 , 20.  , 30.  , 50.  ],
       [ 4.  , 15.8 , 15.1 ,  0.87,  2.2 ,  3.5 , 20.  , 30.  , 50.  ],
       [ 8.  , 15.9 , 14.9 ,  0.92,  2.2 ,  3.6 , 20.  , 30.  , 50.  ],
       [12.  , 15.9 , 14.7 ,  0.92,  2.2 ,  3.6 , 20.  , 30.  , 50.  ],
       [16.  , 16.  , 14.6 ,  0.92,  2.3 ,  3.6 , 20.  , 30.  , 50.  ],
       [20.  , 16.1 , 14.4 ,  0.97,  2.3 ,  3.7 , 20.  , 30.  , 50.  ],
       [24.  , 16.1 , 14.2 ,  1.  ,  2.4 ,  3.8 , 20.  , 30.  , 50.  ],
       [28.  , 16.2 , 14.1 ,  1.  ,  2.4 ,  3.8 , 20.  , 30.  , 50.  ],
       [32.  , 16.2 , 13.9 ,  1.1 ,  2.5 ,  3.9 , 20.  , 30.  , 50.  ],
       [36.  , 16.2 , 13.8 ,  1.1 ,  2.5 ,  3.9 , 20.  , 30.  , 50.  ],
       [40.  , 16.3 , 13.7 ,  1.1 ,  2.5 ,  3.9 , 20.  , 30.  , 50.  ]])

In [6]:
table3_ref = np.loadtxt(open("kosarim_table_3.csv", "rb"), delimiter=" ", skiprows=1)
table3_ref

array([[ 0.  , 17.8 , 16.8 ,  0.79,  2.9 ,  5.2 , 20.  , 30.  , 50.  ],
       [ 4.  , 19.  , 15.7 ,  0.9 ,  3.1 ,  5.3 , 20.  , 30.  , 50.  ],
       [ 8.  , 20.  , 15.2 ,  0.95,  3.2 ,  5.4 , 20.  , 30.  , 50.  ],
       [12.  , 20.6 , 14.8 ,  1.  ,  3.3 ,  5.5 , 20.  , 30.  , 50.  ],
       [16.  , 20.4 , 14.5 ,  1.2 ,  3.5 ,  5.8 , 20.  , 30.  , 50.  ],
       [20.  , 20.  , 14.2 ,  1.4 ,  3.7 ,  6.1 , 20.  , 30.  , 50.  ],
       [24.  , 19.6 , 14.1 ,  1.5 ,  3.9 ,  6.4 , 20.  , 30.  , 50.  ],
       [28.  , 19.2 , 14.  ,  1.6 ,  4.1 ,  6.6 , 20.  , 30.  , 50.  ],
       [32.  , 18.8 , 13.9 ,  1.8 ,  4.3 ,  6.8 , 20.  , 30.  , 50.  ],
       [36.  , 18.4 , 13.8 ,  1.8 ,  4.4 ,  6.9 , 20.  , 30.  , 50.  ],
       [40.  , 18.  , 13.7 ,  1.9 ,  4.5 ,  7.3 , 20.  , 30.  , 50.  ]])

In [7]:
table4_ref = np.loadtxt(open("kosarim_table_4.csv", "rb"), delimiter=" ", skiprows=1)
table4_ref

array([[ 0.  , 18.7 , 19.1 ,  0.13,  1.  ,  2.  , 20.  , 30.  , 50.  ],
       [ 4.  , 18.5 , 18.8 ,  0.16,  1.1 ,  2.1 , 20.  , 30.  , 50.  ],
       [ 8.  , 18.3 , 18.4 ,  0.2 ,  1.2 ,  2.2 , 20.  , 30.  , 50.  ],
       [12.  , 18.1 , 17.9 ,  0.26,  1.3 ,  2.3 , 20.  , 30.  , 50.  ],
       [16.  , 17.9 , 17.4 ,  0.32,  1.4 ,  2.5 , 20.  , 30.  , 50.  ],
       [20.  , 17.7 , 16.9 ,  0.39,  1.5 ,  2.6 , 20.  , 30.  , 50.  ],
       [24.  , 17.5 , 16.4 ,  0.47,  1.6 ,  2.8 , 20.  , 30.  , 50.  ],
       [28.  , 17.1 , 15.9 ,  0.56,  1.7 ,  2.9 , 20.  , 30.  , 50.  ],
       [32.  , 16.9 , 15.4 ,  0.65,  1.9 ,  3.1 , 20.  , 30.  , 50.  ],
       [36.  , 16.7 , 15.  ,  0.75,  2.  ,  3.3 , 20.  , 30.  , 50.  ],
       [40.  , 16.5 , 14.7 ,  0.83,  2.1 ,  3.4 , 20.  , 30.  , 50.  ]])

In [8]:
"Note this equation is not used here."
def f_eqn6(x: float):
    "Equation 6 of Kosarim, et al., for s electrons."
    return (10*(x-1))/(pi*x*(x+8))

In [9]:
"Note this equation is not used here."
def f_eqn7(x: float):
    "Equation 7 of Kosarim, et al., for p electrons."
    return (10*(x-1))/(pi*(x+10)*(x+2))

In [10]:
def f_eqn15(x: float):
    "Equation 15 of Kosarim, et al., for all electrons."
    return (6*(x-1))/(pi*(x+1.5)*(x+9))

In [11]:
def sigma_ion(f, n: int, E: float, J_v_vp: float, J_v_vpp: float):
    """Compute cross-sections (10^-17 cm^2) of ionization transitions for Tables 2-4 of Kosarim, et al."""
    return (cm_per_m**2 * eV_per_J**2)/(1.0E-17)  * (1./(4.*pi*e0)**2) * \
        ((n*e**4)/2.) * ( f(E/J_v_vp)/(J_v_vp**2) + f(E/J_v_vpp)/(J_v_vpp**2) )

In [12]:
def calculate_kosarim_table_sigmas_unscaled(table_ref, f_eqn, n):
    sigmas = np.ones((len(table_ref),3))
    
    for i in range(len(table_ref)):
        for j in range(3):
            sigmas[i,j] = sigma_ion(f=f_eqn, n=n, E=table_ref[i,j+6], J_v_vp=table_ref[i,1], J_v_vpp=table_ref[i,2])
                
    return sigmas

In [13]:
sigmas_X=calculate_kosarim_table_sigmas_unscaled(table2_ref, f_eqn15, 2)
sigmas_A=calculate_kosarim_table_sigmas_unscaled(table3_ref, f_eqn15, 4)
sigmas_B=calculate_kosarim_table_sigmas_unscaled(table4_ref, f_eqn15, 2)

In [14]:
sigma_tot = np.array([1.74, 6.10, 10.90])

In [15]:
N_20eV = 1.74/(sigmas_X[0,0]+sigmas_A[0,0]+sigmas_B[0,0])
N_30eV = 6.10/(sigmas_X[0,1]+sigmas_A[0,1]+sigmas_B[0,1])
N_50eV = 10.9/(sigmas_X[0,2]+sigmas_A[0,2]+sigmas_B[0,2])

In [16]:
np.set_printoptions(precision=2)

In [17]:
sigmas_X_scaled = np.column_stack((N_20eV*sigmas_X[...,0], N_30eV*sigmas_X[...,1], N_50eV*sigmas_X[...,2]))
sigmas_X_scaled

array([[0.82, 2.11, 3.47],
       [0.87, 2.18, 3.56],
       [0.89, 2.21, 3.59],
       [0.93, 2.27, 3.66],
       [0.94, 2.27, 3.67],
       [0.97, 2.31, 3.71],
       [1.01, 2.37, 3.78],
       [1.02, 2.38, 3.8 ],
       [1.07, 2.45, 3.87],
       [1.09, 2.48, 3.91],
       [1.11, 2.5 , 3.93]])

In [18]:
sigmas_A_scaled = np.column_stack((N_20eV*sigmas_A[...,0], N_30eV*sigmas_A[...,1], N_50eV*sigmas_A[...,2]))
sigmas_A_scaled

array([[0.79, 2.95, 5.33],
       [0.9 , 3.08, 5.48],
       [0.95, 3.12, 5.49],
       [1.04, 3.22, 5.6 ],
       [1.18, 3.42, 5.85],
       [1.35, 3.68, 6.16],
       [1.44, 3.81, 6.34],
       [1.53, 3.96, 6.53],
       [1.63, 4.11, 6.73],
       [1.74, 4.28, 6.93],
       [1.86, 4.45, 7.15]])

In [19]:
sigmas_B_scaled = np.column_stack((N_20eV*sigmas_B[...,0], N_30eV*sigmas_B[...,1], N_50eV*sigmas_B[...,2]))
sigmas_B_scaled

array([[0.13, 1.04, 2.1 ],
       [0.16, 1.1 , 2.17],
       [0.21, 1.17, 2.27],
       [0.26, 1.26, 2.39],
       [0.32, 1.36, 2.52],
       [0.39, 1.47, 2.66],
       [0.47, 1.59, 2.82],
       [0.58, 1.75, 3.02],
       [0.68, 1.9 , 3.2 ],
       [0.77, 2.03, 3.37],
       [0.85, 2.15, 3.51]])

In [20]:
print('sigmas_X_scaled RMSE: {:3.4f}'.format(sqrt(mse(sigmas_X_scaled,table2_ref[...,3:6]))))

sigmas_X_scaled RMSE: 0.0306


In [21]:
print('sigmas_A_scaled RMSE: {:3.4f}'.format(sqrt(mse(sigmas_A_scaled,table3_ref[...,3:6]))))

sigmas_A_scaled RMSE: 0.0881


In [22]:
print('sigmas_B_scaled RMSE: {:3.4f}'.format(sqrt(mse(sigmas_B_scaled,table4_ref[...,3:6]))))

sigmas_B_scaled RMSE: 0.0523


In [23]:
table5_ref = np.loadtxt(open("kosarim_table_5.csv", "rb"), delimiter=" ", skiprows=1)
table5_ref

array([[ 0. ,  9.6, 11.6,  1.4,  3.1,  4.2, 15. , 25. , 40. ],
       [ 4. ,  8.8, 12. ,  1.7,  3.5,  4.6, 15. , 25. , 40. ],
       [ 8. ,  8.2, 12.4,  2.1,  4. ,  5.1, 15. , 25. , 40. ],
       [12. ,  7.6, 12.8,  2.6,  4.5,  5.6, 15. , 25. , 40. ],
       [16. ,  7.1, 13.2,  3. ,  5.1,  6.2, 15. , 25. , 40. ],
       [20. ,  6.8, 13.6,  3.4,  5.5,  6.6, 15. , 25. , 40. ],
       [24. ,  6.6, 14. ,  3.7,  5.8,  6.8, 15. , 25. , 40. ]])

In [24]:
sigmas_triplet=calculate_kosarim_table_sigmas_unscaled(table5_ref, f_eqn15, 2)
sigmas_triplet

array([[1.05, 2.28, 2.99],
       [1.29, 2.58, 3.29],
       [1.55, 2.88, 3.57],
       [1.9 , 3.28, 3.95],
       [2.29, 3.7 , 4.33],
       [2.57, 3.99, 4.59],
       [2.78, 4.2 , 4.77]])

In [25]:
"""
Need to figure out how to scale the triplet sigmas. For now, use
the same scaling factors as above even though we know that's wrong.
"""
N_15eV = 1.74/(sigmas_X[0,0]+sigmas_A[0,0]+sigmas_B[0,0])
N_25eV = 6.10/(sigmas_X[0,1]+sigmas_A[0,1]+sigmas_B[0,1])
N_40eV = 10.9/(sigmas_X[0,2]+sigmas_A[0,2]+sigmas_B[0,2])

In [26]:
sigmas_triplet_scaled = \
    np.column_stack((N_15eV*sigmas_triplet[...,0], N_25eV*sigmas_triplet[...,1], N_40eV*sigmas_triplet[...,2]))
sigmas_triplet_scaled

array([[ 2.67,  5.98,  8.3 ],
       [ 3.3 ,  6.76,  9.13],
       [ 3.95,  7.54,  9.91],
       [ 4.85,  8.58, 10.94],
       [ 5.84,  9.69, 12.02],
       [ 6.55, 10.45, 12.73],
       [ 7.07, 10.99, 13.22]])

In [27]:
print('sigmas_triplet_scaled RMSE: {:3.4f}'.format(sqrt(mse(sigmas_triplet_scaled,table5_ref[...,3:6]))))

sigmas_triplet_scaled RMSE: 4.1651


In [28]:
import cse

In [29]:
from scipy.interpolate import splrep, splev
import matplotlib.pyplot as plt
import sys

In [37]:
# Panda's csv reader is much better than numpy's
df = pd.read_csv('kosarim_table_1.csv',sep=' ')
table1_ref = np.array(df)
table1_ref

#N_2 (X^1Sigma^+_g)
we = 2359
wexe = 14.3
Be = 1.998
ae = 1.73E-2
De = 79884
# reduced mass - see Huber+Herzberg
μ = 7.99745751

In [36]:
table1_ref[0,1:4]

array([0, 2359, 14.3], dtype=object)

In [35]:
Te,we,wexe,Be,ae,De = table1_ref[0,...]

array(['$N_2(X^1\\Sigma_g^+)$', 0, 2359, 14.3, 1.9980000000000002, 1.73,
       79884], dtype=object)

In [33]:
we, wexe, Be = table1_ref

array([['$N_2(X^1\\Sigma_g^+)$', 0, 2359, 14.3, 1.9980000000000002, 1.73,
        79884],
       ['$N_2^+(X^2\\Sigma_g^+)$', 0, 2207, 16.1, 1.932, 1.88, 71387],
       ['$N_2^+(A^2\\Pi_u)$', 9167, 1904, 15.0, 1.744, 1.88, 62217],
       ['$N_2^+(B^2\\Sigma_u^+)$', 25461, 2420, 23.2, 2.0709999999999997,
        1.4, 45919]], dtype=object)

In [ ]:
v = np.concatenate(([-0.5], np.arange(11)), axis=None)

In [ ]:
Gv = we*(v+1/2) - wexe*(v+1/2)**2

In [ ]:
Gv

In [ ]:
Bv = Be - ae*(v+1/2)

In [ ]:
Bv

In [ ]:
fn = 'data/n2.dat'
np.savetxt(fn,np.column_stack((v, Gv, Bv)))

In [ ]:
try:
    vv, Gv, Bv = np.loadtxt(fn, unpack=True)
except FileNotFoundError:
    print(f"RKR: file '{fn:s}' not found")

In [ ]:
# reduced mass - see Huber+Herzberg - default is O2
#μ = input("RKR: Molecule reduced mass [7.99745751]: ")
#μ = 7.99745751 if μ == '' else float(μ)
μ = 14.007/2.

In [ ]:
# outer limb extension
#limb = input("RKR: Outer-limb LeRoy(L) or Morse(M) [L]: ")
#if limb == '':
#    limb = 'L'
limb = 'L'

In [ ]:
R, PEC, RTP, PTP = cse.tools.RKR.rkr(μ, vv, Gv, Bv, De, limb, dv=0.1,
                                     Rgrid=np.arange(0.005, 10.004, 0.005))

In [38]:
data = np.column_stack((R.T, PEC.T))
np.savetxt("data/N2_RKR.dat", data)
print("RKR: potential curve written to 'data/N2_RKR.dat'")

NameError: name 'R' is not defined

In [ ]:
plt.plot(R, PEC, label='RKR potential curve')
plt.plot(RTP[::10], PTP[::10], 'o', label='turning points')
plt.legend()
plt.axis(xmin=0.8, xmax=4, ymin=-0.1, ymax=12)
plt.title("N2_RKR.py")

plt.xlabel(r"R($\AA$)")
plt.ylabel("E(eV)")

plt.savefig("output/N2_RKR.png", dpi=75)
plt.show()

In [ ]:
RTP